export const formJs = `/* This JavaScript was generated by Indiga */

const toggleSwitches = document.querySelectorAll(".indiga-toggle-switch");

toggleSwitches.forEach((toggle) => {
	addFunctionToToggle(toggle);
});

function addFunctionToToggle(toggle) {
	const toggleButtonWrapper = toggle.querySelector(".indiga-toggle-switch-button-wrapper");
	toggleButtonWrapper.style.display = "flex";

	const radioButtons = toggle.querySelector(".wpcf7-form-control-wrap");
	radioButtons.style.display = "none";

	const toggleButton = toggleButtonWrapper.querySelector("button");

	toggleButton.addEventListener("click", () => {
		const isChecked = toggleButtonWrapper.getAttribute("data-checked") === "true";
		toggleButtonWrapper.setAttribute("data-checked", !isChecked);

		const toggleButtonLabel = toggle.querySelector(".indiga-toggle-button-label");
		if (!isChecked === true) {
			const firstRadio = radioButtons.querySelector('.first input[type="radio"]');
			firstRadio.checked = true;
			toggleButtonLabel.textContent = firstRadio.value;
            toggleButton.setAttribute(
                "aria-description",
                "Currently toggled: " + firstRadio.value
            );
		} else {
			const lastRadio = radioButtons.querySelector('.last input[type="radio"]');
			lastRadio.checked = true;
			toggleButtonLabel.textContent = lastRadio.value;
            toggleButton.setAttribute(
                "aria-description",
                "Currently toggled: " + lastRadio.value
            );
		}
	});
}

/* End of JavaScript generated by Indiga */`