export const defaultCss = {
    "backgroundColor": "transparent",
    "maxWidth": "750",
    "borderRadius": "0",
    "bodyPaddingRight": "0",
    "bodyPaddingLeft": "0",
    "bodyPaddingBottom": "0",
    "bodyPaddingTop": "0",
    "formTitleColor": "#000000",
    "formTitleFontSize": "30",
    "formTitleBold": "bold",
    "h2Color": "#000000",
    "h2FontSize": "24",
    "h2Bold": "bold",
    "h3Color": "#000000",
    "h3FontSize": "20",
    "h3Bold": "bold",
    "h4Color": "#000000",
    "h4FontSize": "18",
    "h4Bold": "bold",
    "textBlockColor": "#000000",
    "textBlockFontSize": "16",
    "textBlockBackgroundColor": "transparent",
    "textBlockPaddingTop": "0",
    "textBlockPaddingRight": "0",
    "textBlockPaddingBottom": "0",
    "textBlockPaddingLeft": "0",
    "textBlockBorderRadius": "0",
    "labelColor": "#000000",
    "labelFontSize": "16",
    "labelBold": "normal",
    "textFieldBackgroundColor": "#ffffff",
    "textFieldColor": "#000000",
    "textFieldFontSize": "16",
    "textFieldBold": "normal",
    "textFieldBorderStyle": "solid",
    "textFieldBorderColor": "#cccccc",
    "textFieldBorderWidth": "1",
    "textFieldBorderRadius": "4",
    "textFieldPaddingTop": "8",
    "textFieldPaddingRight": "8",
    "textFieldPaddingBottom": "8",
    "textFieldPaddingLeft": "8",
    "inputFieldBorderStyle": "solid",
    "inputFieldBorderColor": "#cccccc",
    "inputFieldBorderWidth": "1",
    "inputFieldBorderRadius": "8",
    "inputFieldPaddingTop": "16",
    "inputFieldPaddingRight": "16",
    "inputFieldPaddingBottom": "16",
    "inputFieldPaddingLeft": "16",
    "radioCheckboxSize": "24",
    "radioCheckboxFontSize": "16",
    "radioCheckboxGap": "4",
    "toggleOnColor": "#3b82f6",
    "toggleOffColor": "#cbd5e1",
    "toggleLabelBold": "bold",
    "toggleLabelFontSize": "16",
}

export const formCss = `/* This CSS was generated by Indiga */

.wpcf7-form {
    background-color: [[backgroundColor]];
    border-radius: [[borderRadius]]px;
    padding-top: [[bodyPaddingTop]]px;
    padding-right: [[bodyPaddingRight]]px;
    padding-bottom: [[bodyPaddingBottom]]px;
    padding-left: [[bodyPaddingLeft]]px;
}

.indiga-field p,
.indiga-field legend {
	margin: 0;
	padding: 0;
}

fieldset.indiga-field {
    border: none;
    padding: 0;
}

.indiga-label,
p.indiga-label {
	display: block;
	margin-bottom: 4px;
    color: [[labelColor]];
    font-size: [[labelFontSize]]px;
    font-weight: [[labelBold]];
}

.indiga-form-title {
    font-size: [[formTitleFontSize]]px;
    font-weight: [[formTitleBold]];
    color: [[formTitleColor]];
}

h2.indiga-heading {
    font-size: [[h2FontSize]]px;
    font-weight: [[h2Bold]];
    color: [[h2Color]];
}

h3.indiga-heading {
    font-size: [[h3FontSize]]px;
    font-weight: [[h3Bold]];
    color: [[h3Color]];
}

h4.indiga-heading {
    font-size: [[h4FontSize]]px;
    font-weight: [[h4Bold]];
    color: [[h4Color]];
}

.indiga-text-block {
    font-size: [[textBlockFontSize]]px;
    color: [[textBlockColor]];
    background-color: [[textBlockBackgroundColor]];
    padding-top: [[textBlockPaddingTop]]px;
    padding-right: [[textBlockPaddingRight]]px;
    padding-bottom: [[textBlockPaddingBottom]]px;
    padding-left: [[textBlockPaddingLeft]]px;
    border-radius: [[textBlockBorderRadius]]px;
}

.indiga-note-wrapper {
	margin: 10px 0;
    display: block;
}

.indiga-note {
	display: block;
	font-size: 14px;
	color: #555;
}

.indiga-checkboxes-group .indiga-label,
.indiga-radio-buttons-group .indiga-label,
.indiga-toggle-switch .indiga-label {
	margin-bottom: 16px;
}

.indiga-checkboxes-group .wpcf7-form-control-wrap,
.indiga-radio-buttons-group .wpcf7-form-control-wrap,
.indiga-toggle-switch .wpcf7-form-control-wrap {
	margin-left: 8px;
}

.wpcf7-form-control-wrap {
	display: block;
}

.wpcf7-form-control {
	border: 1px solid #ccc;
	width: 100%;
	border-radius: 4px;
	padding: 8px;
	font-size: 16px;
}

.wpcf7-radio,
.wpcf7-checkbox {
	border: none;
	padding: 0;
	display: flex;
	flex-direction: column;
	gap: 4px;
}

.wpcf7-list-item {
	display: block;
	margin-left: 4px;
}

.wpcf7-list-item label {
	display: inline-flex;
	gap: 8px;
	cursor: pointer;
	align-items: center;
}

.wpcf7-list-item input[type="radio"],
.wpcf7-list-item input[type="checkbox"] {
	width: [[radioCheckboxSize]]px;
	height: [[radioCheckboxSize]]px;
}

.wpcf7-file::file-selector-button {
	background-color: #e0e0e1;
	padding: 8px 16px;
	border: none;
	border-radius: 4px;
	font-weight: bold;
	cursor: pointer;
	margin-right: 16px;
}

.wpcf7-submit {
	background-color: #1d4ed8;
	color: white;
	padding: 8px 16px;
	border: none;
	border-radius: 4px;
	font-weight: bold;
	cursor: pointer;
	margin-right: 16px;
	width: unset;
}

.indiga-toggle-switch-button {
	display: block;
	background: #cbd5e1;
	width: 60px;
	height: 36px;
	border-radius: 1000px;
	position: relative;
	border: none;
	cursor: pointer;
}

.indiga-toggle-switch-button-wrapper,
.indiga-toggle-switch-button-wrapper > * {
	display: flex;
	align-items: center;
	gap: 8px;
	font-weight: bold;
	margin: 0;
}

.indiga-toggle-switch-button-inner {
	background: white;
	width: 28px;
	height: 28px;
	display: block;
	border-radius: 50%;
	position: absolute;
	top: 4px;
	left: 4px;
	box-shadow: 1px 1px 2px rgba(0, 0, 0, 0.2);
	transition: 0.3s ease-out;
}

[data-checked="true"] .indiga-toggle-switch-button {
	background: #3b82f6;
}

[data-checked="true"] .indiga-toggle-switch-button .indiga-toggle-switch-button-inner {
	transform: translateX(24px);
}

.indiga-file-upload {
	border: 1px solid #ccc;
	padding: 16px;
	border-radius: 8px;
}

.wpcf7-date {
	width: 150px;
}

.wpcf7-not-valid-tip {
    background: #fee2e2;
    padding: 8px 13px;
    border-radius: 5px;
    font-size: 13px;
    font-weight: bold;
    margin-top: 5px;
}

.wpcf7 form .wpcf7-response-output {
    padding: 16px 20px;
    border-radius: 5px;
    font-size: 15px;
    font-weight: bold;
    border: none;
    margin: 0 0 20px;
    
}

.wpcf7 form.sent .wpcf7-response-output {
    background: #d1fae5;
    color: #047857;
}

.wpcf7 form.invalid .wpcf7-response-output {
    background: #fef3c7;
    color: #92400e;
}

.indiga-field {
    margin: 20px 0;
}

.wpcf7-spinner::before {
	display: none;
}

p:has(.wpcf7-spinner) {
	display: inline-flex;
    align-items: center;
    gap: 10px;
}

.wpcf7-spinner {
    width: 32px;
    height: 32px;
    border: 5px solid #FFF;
    border-bottom-color: #1d4ed8;
    border-radius: 50%;
    display: inline-block;
    box-sizing: border-box;
    animation: rotation 1s linear infinite;
    opacity: 1;
    background: none;
    padding: 0;
    margin: 0;
    position: unset;
}

@keyframes rotation {
    0% {
        transform: rotate(0deg);
    }
    100% {
        transform: rotate(360deg);
    }
}

/* End of CSS generated by Indiga */`;